include: "../config.py"

conda:  "../graph_conda.yaml"


rule all:
    input:
        OUTDIR+"/simplified_%d.asqg" % (OVERLAP),
        OUTDIR+"/simplified_%d_counts.tsv" % (OVERLAP)



rule simplify:
    input:
        graph = OUTDIR+"/sga/merged.rmdup_%d.asqg" % (OVERLAP),
        c = OUTDIR+"/sga/merged.rmdup_%d_counts.tsv" % (OVERLAP),
    output:
        graph = OUTDIR+"/simplified_%d.asqg" % (OVERLAP),
        c = OUTDIR+"/simplified_%d_counts.tsv" % (OVERLAP),
    shell:
        "python clean_graph.py {input.graph} -c {input.c} -o {output}"
    



rule longest:
    input:
        graph = OUTDIR+"/simplified_%d.asqg" % (OVERLAP),
        c = OUTDIR+"/simplified_%d_counts.tsv" % (OVERLAP)
    output:
          OUTDIR+"/longest.fa"  
    shell:
        "run_heuristics.py  {input.graph} -c {input.c} -o {output} -t longest"

# rule longestfc:
#     input:
#         graph = OUTDIR+"/simplified_%d.asqg" % (OVERLAP),
#         c = OUTDIR+"/simplified_%d_counts.tsv" % (OVERLAP)

# rule bestfc:
#     input:
#         graph = OUTDIR+"/simplified_%d.asqg" % (OVERLAP),
#         c = OUTDIR+"/simplified_%d_counts.tsv" % (OVERLAP)